// hub.js — generated by Orion Admin Dashboard
// Last updated: 07/04/2026, 12:19:45
// DO NOT EDIT MANUALLY — use the admin dashboard

const HUB_DATA = {
  "news": [],
  "vault": [],
  "social": [],
  "images": [
    {
      "id": "mnoj0qyce62n",
      "url": "https://www.youtube.com/watch?v=4PeEdrTPFFs",
      "label": "sorters",
      "page": "home",
      "section": "",
      "added": "2026-04-07"
    }
  ],
  "generated": "2026-04-07T11:19:45.126Z"
};

// Make available globally
if(typeof window !== 'undefined') window.HUB_DATA = HUB_DATA;
